export const MS_OPTION_LOOKUP = {
  key_rings: [
    'Thieves Hideout',
    'Treasure Chest Game',
    'Forest Temple',
    'Fire Temple',
    'Water Temple',
    'Shadow Temple',
    'Spirit Temple',
    'Bottom of the Well',
    'Gerudo Training Ground',
    'Ganons Castle',
  ],
  silver_rupee_pouches: [
    'Dodongos Cavern Staircase',
    'Ice Cavern Spinning Scythe',
    'Ice Cavern Push Block',
    'Bottom of the Well Basement',
    'Shadow Temple Scythe Shortcut',
    'Shadow Temple Invisible Blades',
    'Shadow Temple Huge Pit',
    'Shadow Temple Invisible Spikes',
    'Gerudo Training Ground Slopes',
    'Gerudo Training Ground Lava',
    'Gerudo Training Ground Water',
    'Spirit Temple Child Early Torches',
    'Spirit Temple Adult Boulders',
    'Spirit Temple Lobby and Lower Adult',
    'Spirit Temple Sun Block',
    'Spirit Temple Adult Climb',
    'Ganons Castle Spirit Trial',
    'Ganons Castle Light Trial',
    'Ganons Castle Fire Trial',
    'Ganons Castle Shadow Trial',
    'Ganons Castle Water Trial',
    'Ganons Castle Forest Trial',
  ],
  dungeon_shortcuts: [
    'Deku Tree',
    'Dodongos Cavern',
    'Jabu Jabus Belly',
    'Forest Temple',
    'Fire Temple',
    'Water Temple',
    'Shadow Temple',
    'Spirit Temple',
  ],
  mq_dungeons_specific: [
    'Deku Tree',
    'Dodongos Cavern',
    'Jabu Jabus Belly',
    'Forest Temple',
    'Fire Temple',
    'Water Temple',
    'Shadow Temple',
    'Spirit Temple',
    'Bottom of the Well',
    'Ice Cavern',
    'Gerudo Training Ground',
    'Ganons Castle',
  ],
  empty_dungeons_specific: [
    'Deku Tree',
    'Dodongos Cavern',
    'Jabu Jabus Belly',
    'Forest Temple',
    'Fire Temple',
    'Water Temple',
    'Shadow Temple',
    'Spirit Temple',
  ],
  mix_entrance_pools: ['Interior', 'GrottoGrave', 'Dungeon', 'Overworld'],
  spawn_positions: ['child', 'adult'],
  shuffle_child_trade: [
    'Weird Egg',
    'Chicken',
    'Zeldas Letter',
    'Keaton Mask',
    'Skull Mask',
    'Spooky Mask',
    'Bunny Hood',
    'Goron Mask',
    'Zora Mask',
    'Gerudo Mask',
    'Mask of Truth',
  ],
  minor_items_as_major_chest: ['bombchus', 'shields', 'capacity'],
  misc_hints: [
    'altar',
    'dampe_diary',
    'ganondorf',
    'warp_songs_and_owls',
    '10_skulltulas',
    '20_skulltulas',
    '30_skulltulas',
    '40_skulltulas',
    '50_skulltulas',
    'frogs2',
    'mask_shop',
    'unique_merchants',
  ],
  adult_trade_start: [
    'Pocket Egg',
    'Pocket Cucco',
    'Cojiro',
    'Odd Mushroom',
    'Odd Potion',
    'Poachers Saw',
    'Broken Sword',
    'Prescription',
    'Eyeball Frog',
    'Eyedrops',
    'Claim Check',
  ],
  potcrate_textures_specific: ['major', 'bosskeys', 'keys', 'tokens', 'hearts'],
  chest_textures_specific: ['major', 'bosskeys', 'keys', 'tokens', 'hearts'],
  empty_dungeons_rewards: [
    'Kokiri Emerald',
    'Goron Ruby',
    'Zora Sapphire',
    'Light Medallion',
    'Forest Medallion',
    'Fire Medallion',
    'Water Medallion',
    'Shadow Medallion',
    'Spirit Medallion',
  ],
  ocarina_songs: ['frog', 'warp', 'frogs2'],
  shuffle_fairies: [
    'GossipFairy',
    'ButterflyFairy',
    'SunsStormsFairy',
    'FountainFairy',
    'BeanPlantFairy',
  ],
  random_starting_items_exclude: [
    'songs',
    'bombchus',
    'shields',
    'deku_upgrades',
    'health_upgrades',
    'junk',
  ],
};

export const INVALID_SETTINGS = [
  'mq_dungeons_specific',
  'empty_dungeons_specific',
  'misc_hints',
  'empty_dungeons_rewards',
];
